server:
  port: ${SERVER_PORT:8000}
spring:
  application:
    name: "gateway-server"
  config:
    import: "configserver:"
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
